# Generated by Django 6.0.1 on 2026-01-21 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='compliance.application'),
        ),
    ]
