# Generated by Django 6.0.1 on 2026-01-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('application_type', models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile Application'), ('api', 'API/Service'), ('database', 'Database'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], default='web', max_length=20)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development'), ('testing', 'Testing')], default='production', max_length=20)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, help_text='Application URL if applicable')),
                ('version', models.CharField(blank=True, max_length=50)),
                ('data_categories', models.TextField(blank=True, help_text='Types of personal data processed')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Overall compliance percentage', max_digits=5)),
                ('critical_score', models.DecimalField(decimal_places=2, help_text='Compliance percentage for critical items', max_digits=5, null=True)),
                ('major_score', models.DecimalField(decimal_places=2, help_text='Compliance percentage for major items', max_digits=5, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compliance Score',
                'verbose_name_plural': 'Compliance Scores',
                'db_table': 'compliance_scores',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('screenshot', 'Screenshot'), ('policy', 'Policy Document'), ('log', 'System Log'), ('certificate', 'Certificate'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence Files',
                'db_table': 'evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Remediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('deferred', 'Deferred'), ('wont_fix', "Won't Fix")], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Remediation',
                'verbose_name_plural': 'Remediations',
                'db_table': 'remediations',
                'ordering': ['-created_at'],
            },
        ),
    ]
